export const MAP_CONFIG = {
  width: 800,
  height: 600,
  shops: [
    {
      id: 'xiaomei',
      name: '小美面馆',
      x: 320,
      y: 200,
      width: 120,
      height: 100,
      emoji: '🍜',
      href: '/shop/xiaomei',
    },
    {
      id: 'shop2',
      name: '神秘小店',
      x: 560,
      y: 350,
      width: 120,
      height: 100,
      emoji: '🔒',
      href: null,
      locked: true,
    },
    {
      id: 'shop3',
      name: '???',
      x: 100,
      y: 380,
      width: 120,
      height: 100,
      emoji: '🔒',
      href: null,
      locked: true,
    },
  ],
  playerStart: { x: 400, y: 450 },
  walkBounds: { minX: 40, maxX: 760, minY: 80, maxY: 560 },
};
